[project]
name = "pdf-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydyf>=0.11.0",
    "ruff>=0.14.0",
    "sanic>=25.3.0",
    "weasyprint>=66.0",
]
